PRODUCT_COPY_FILES += \
	#proprietary/vendor/app/
	proprietary/vendor/bin/hw/android.hardware.audio@2.0-service:system/vendor/bin/hw/android.hardware.audio@2.0-service \
	proprietary/vendor/bin/hw/android.hardware.audio@2.0-service-mediatek:system/vendor/bin/hw/android.hardware.audio@2.0-service-mediatek
	proprietary/vendor/bin/hw/android.hardware.bluetooth@1.0-service-mediatek:system/vendor/bin/hw/android.hardware.bluetooth@1.0-service-mediatek
	proprietary/vendor/bin/hw/android.hardware.broadcastradio@1.1-service:system/vendor/bin/hw/android.hardware.broadcastradio@1.1-service
	proprietary/vendor/bin/hw/android.hardware.cas@1.0-service:system/vendor/bin/hw/android.hardware.cas@1.0-service
	proprietary/vendor/bin/hw/android.hardware.configstore@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.drm@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.drm@1.0-service.widevine:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.graphics.allocator@2.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.graphics.composer@2.1-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.keymaster@3.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.light@2.0-service-mediatek:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.media.omx@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.memtrack@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.sensors@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.thermal@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.vibrator@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/android.hardware.wifi@1.0-service:system/vendor/bin/hw/android.hardware.
	proprietary/vendor/bin/hw/camerahalserver:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/macloader:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/mfgloader:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/mnld:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/mtk_agpsd:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/power_native_test:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/rild:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/vendor.mediatek.hardware.keymaster_attestation@1.1-service:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/vendor.mediatek.hardware.power@1.1-service:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/vendor.samsung.hardware.biometrics.fingerprint@2.1-service:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/vendor.samsung.hardware.gnss@1.0-service:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/vendor.samsung.hardware.miscpower@1.0-service:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/vendor.samsung.hardware.vibrator@1.0-service:system/vendor/bin/hw/
	proprietary/vendor/bin/hw/wpa_supplicant:system/vendor/bin/hw/
	proprietary/vendor/etc/
	proprietary/vendor/lib/
	#from here lib starts
	proprietary/lib/drm/libfwdlockengine.so:system/lib/drm
	proprietary/lib/drm/libomaplugin.so:system/lib/drm
        proprietary/lib/egl/libGLES_android.so:system/lib/egl
	proprietary/lib/hw/android.hidl.memory@1.0-impl.so:system/lib/hw
	proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw
	proprietary/lib/hw/audio.playback_record.default.so:system/lib/hw
	proprietary/lib/hw/bluetooth.default.so:system/lib/hw
	proprietary/lib/hw/face.default.so:system/lib/hw
	proprietary/lib/hw/keystore.default.so:system/lib/hw
	proprietary/lib/hw/keystore.mt6757.so:system/lib/hw
	proprietary/lib/mtkdrm/libdrmctaplugin.so:system/lib/mtkdrm
	proprietary/lib/mtkdrm/libdrmmtkplugin.so:system/lib/mtkdrm
	proprietary/lib/mtkdrm/libdrmmtkplugin.so:system/lib/
	proprietary/lib/slocation/libsgeo.so:system/lib/slocation
	proprietary/lib/soundfx/libaudioeffectoffload.so:system/lib/soundfx
        proprietary/lib/soundfx/libaudiosa.so:system/lib/soundfx
	proprietary/lib/soundfx/libaudiosaplus_sec.so:system/lib/soundfx
	proprietary/lib/soundfx/libgearvr.so:system/lib/soundfx
	proprietary/lib/soundfx/libmysound.so:system/lib/soundfx
	proprietary/lib/soundfx/libmyspace.so:system/lib/soundfx
	proprietary/lib/soundfx/libplaybackrecorder.so:system/lib/soundfx
	proprietary/lib/soundfx/libsamsungSoundbooster_plus.so:system/lib/soundfx
	proprietary/lib/vndk-sp/android.hardware.graphics.allocator@2.0.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/android.hardware.graphics.common@1.0.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/android.hardware.graphics.mapper@2.0.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/android.hardware.renderscript@1.0.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/android.hidl.base@1.0.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/android.hidl.memory@1.0.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libRSCpuRef.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libRSDriver.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libRS_internal.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libbacktrace.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libbase.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libbcinfo.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libblas.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libc++.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libcompiler_rt.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libcutils.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libft2.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libhardware.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libhidlbase.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libhidlmemory.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libhidltransport.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libhwbinder.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libion.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/liblzma.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libpng.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libunwind.so:system/lib/vndk-sp
	proprietary/lib/vndk-sp/libutils.so:system/lib/vndk-sp
	proprietary/lib/android.frameworks.displayservice@1.0.so:system/lib
	proprietary/lib/android.frameworks.schedulerservice@1.0.so:system/lib
	proprietary/lib/android.frameworks.sensorservice@1.0.so:system/lib
	proprietary/lib/android.frameworks.vr.composer@1.0.so:system/lib
	proprietary/lib/android.hardware.audio.common@2.0-util.so:system/lib
	proprietary/lib/android.hardware.audio.common@2.0.so:system/lib
	proprietary/lib/android.hardware.audio.effect@2.0.so:system/lib
	proprietary/lib/android.hardware.audio@2.0.so:system/lib
	proprietary/lib/android.hardware.biometrics.fingerprint@2.1.so:system/lib
	proprietary/lib/android.hardware.bluetooth@1.0.so:system/lib
	proprietary/lib/android.hardware.broadcastradio@1.0.so:system/lib
	proprietary/lib/android.hardware.broadcastradio@1.1.so:system/lib
	proprietary/lib/android.hardware.camera.common@1.0.so:system/lib
	proprietary/lib/android.hardware.camera.device@1.0.so:system/lib
	proprietary/lib/android.hardware.camera.device@3.2.so:system/lib
	proprietary/lib/android.hardware.camera.device@3.3.so:system/lib
	proprietary/lib/android.hardware.camera.provider@2.4.so:system/lib
	proprietary/lib/android.hardware.cas.native@1.0.so:system/lib
	proprietary/lib/android.hardware.cas@1.0.so:system/lib
	proprietary/lib/android.hardware.configstore-utils.so:system/lib
	proprietary/lib/android.hardware.configstore@1.0.so:system/lib
	proprietary/lib/android.hardware.contexthub@1.0.so:system/lib
	proprietary/lib/android.hardware.drm@1.0.so:system/lib
	proprietary/lib/android.hardware.dumpstate@1.0.so:system/lib
	proprietary/lib/android.hardware.gatekeeper@1.0.so:system/lib
	proprietary/lib/android.hardware.gnss@1.0.so:system/lib
	proprietary/lib/android.hardware.graphics.allocator@2.0.so:system/lib
	proprietary/lib/android.hardware.graphics.bufferqueue@1.0.so:system/lib
	proprietary/lib/android.hardware.graphics.common@1.0.so:system/lib
	proprietary/lib/android.hardware.graphics.composer@2.1.so:system/lib
	proprietary/lib/android.hardware.graphics.mapper@2.0.so:system/lib
	proprietary/lib/android.hardware.health@1.0.so:system/lib
	proprietary/lib/android.hardware.ir@1.0.so:system/lib
	proprietary/lib/android.hardware.keymaster@3.0.so:system/lib
	proprietary/lib/android.hardware.light@2.0.so:system/lib
	proprietary/lib/android.hardware.media.omx@1.0.so:system/lib
	proprietary/lib/android.hardware.media@1.0.so:system/lib
	proprietary/lib/android.hardware.memtrack@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.power@1.0.so:system/lib
	proprietary/lib/android.hardware.power@1.1.so:system/lib
	proprietary/lib/android.hardware.radio.deprecated@1.0.so:system/lib
	proprietary/lib/android.hardware.radio@1.0.so:system/lib
	proprietary/lib/android.hardware.radio@1.1.so:system/lib
	proprietary/lib/android.hardware.renderscript@1.0.so:system/lib
	proprietary/lib/android.hardware.sensors@1.0.so:system/lib
	proprietary/lib/android.hardware.soundtrigger@2.0.so:system/lib
	proprietary/lib/android.hardware.tetheroffload.config@1.0.so:system/lib
	proprietary/lib/android.hardware.thermal@1.0.so:system/lib
	proprietary/lib/android.hardware.thermal@1.1.so:system/lib
	proprietary/lib/android.hardware.tv.cec@1.0.so:system/lib
	proprietary/lib/android.hardware.tv.input@1.0.so:system/lib
	proprietary/lib/android.hardware.vibrator@1.0.so:system/lib
	proprietary/lib/android.hardware.vibrator@1.1.so:system/lib
	proprietary/lib/android.hardware.vr@1.0.so:system/lib
	proprietary/lib/android.hardware.wifi.offload@1.0.so:system/lib
	proprietary/lib/android.hardware.wifi.supplicant@1.0.so:system/lib
	proprietary/lib/android.hardware.wifi@1.0.so:system/lib
	proprietary/lib/android.hardware.wifi@1.1.so:system/lib
	proprietary/lib/android.hidl.allocator@1.0.so:system/lib
	proprietary/lib/android.hidl.base@1.0.so:system/lib
	proprietary/lib/android.hidl.memory@1.0.so:system/lib
	proprietary/lib/android.hidl.token@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
        proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	proprietary/lib/android.hardware.neuralnetworks@1.0.so:system/lib
	
